Repository Keeper-Security/git-ssh-sign, pull requests merged in 2024-01, with the labels that each got.

#40 Added passphrase handling
  cmd/ssh-sign/main.go
  internal/sign/sign.go
  internal/sign/sign_test.go
  internal/vault/vault.go
Labels: enhancement

#43 Add template files and contribution guide.
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/BUG_REPORT_TEMPLATE.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#45 fix (release): Updated checksum signing
  .github/workflows/release.yml
Labels: github_actions

#47 Remove unused `PublicKey` in `KeyPair`
  internal/vault/vault.go
Labels: go
